config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts ,:newcomments
  
  post "newcomments/createcomment" => "newcomments#createcomment"

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user, :class_name => "User", :foreign_key => "user_id"
	belongs_to :post, :class_name => "Post", :foreign_key => "Post_id"
	validates_presence_of :comment_content
end

app/models/newcomment.rb
class Newcomment < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  belongs_to :post, :class_name => "Post", :foreign_key => "post_id"
  validates_presence_of :comment_content
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comment
	validates_presence_of :title
	validates_presence_of :content
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :post
	has_many :newcomment
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end
  
  def create
    @comment = Comment.new(comment_params)
    #@comment.post_id = current_user.id 
    #@comment.post_id = current_user.id
    @comment.user_id = 1
    @comment.save

    redirect_to :back
  end

  def show

  end 
###################################################
  private

  def comment_params
    params.require(:comment).permit( :comment_content)
  end
end

app/controllers/newcomments_controller.rb
class NewcommentsController < ApplicationController
  def index
    @newcomments = Newcomment.all
  end
  
  def createcomment
    @newcomment = Newcomment.new(newcomment_params)
    #@newcomment.post_id = current_user.id 
    #@newcomment.post_id = current_user.id
    @newcomment.user_id = current_user.id

    @newcomment.save

    redirect_to :back
  end

  def show

  end 
###################################################
  private

  def newcomment_params
    params.require(:newcomment).permit( :comment_content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to :action => :index
  end
  
  def show
    @post = Post.find(params[:id])
    @newcomment = Newcomment.new
    @pastcomment = Newcomment.includes(:user).where( post_id: params[:id])

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    redirect_to :action => :show, :id => @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to :action => :index
  end
  ####
  private

  def post_params
    params.require(:post).permit(:title , :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/newcomments_helper.rb
module NewcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post, :url => { :controller => 'posts', :action => 'update', :id => @post } do |p| %>
    <%= p.label :title, "title" %>
    <%= p.text_field :title %>

    <%= p.label :content, "content" %>
    <%= p.text_area :content %>

    <%= p.submit "Update" %>
<% end %>

app/views/posts/index.html.erb
<% if current_user %>
  <%= link_to('logout', destroy_user_session_path, :method => :delete) %> |
  <%= link_to('forget password', edit_registration_path(:user)) %>
<% else %>
  <%= link_to('sign up', new_registration_path(:user)) %> |
  <%= link_to('login', new_session_path(:user)) %>
<% end %>
</br>
</br>

<%= link_to 'New Post', new_post_path %>
</br>
<% @posts.each do |post| %>
  <li>
    <%= post.title %> </br>
    <%= post.content %> </br>
    <%= post.created_at %> </br>

    <%= link_to "Show", post_path(post) %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= button_to 'Delete', post_path(post), :method => :destroy %>
  </li>
<% end %>
</ul>

app/views/posts/new.html.erb
<%= form_for @post, :url => { :controller => 'posts', :action => 'create' } do |p| %>
    <%= p.label :title, "title" %>
    <%= p.text_field :title %>

    <%= p.label :content, "content" %>
    <%= p.text_area :content %>

    <%= p.submit "Create" %>
<% end %>

app/views/posts/show.html.erb
<%= link_to 'Edit', edit_post_path(@post) %>
<%= button_to 'Delete', post_path(@post), :method => :destroy %>
<%= @post.title %>
<%= simple_format(@post.content) %>
<%= @post.created_at %> </br>

<h3>Comments</h3>

<% @pastcomment.each do |pastcomment| %>
    <li>
    	<%= pastcomment.user.email %>   says
    	<br>
    	<%= pastcomment.comment_content %>
    	<br>  
    	<%= pastcomment.created_at %>
    </li>
    <br>
<% end %>

<%= form_tag({ controller: "newcomments", action: "createcomment" }, method:"post") do %>
    <h4><%= label_tag(:comment_content, "New Comment") %><h4>
    <%= text_area_tag("newcomment[comment_content]")%>


    <%= hidden_field_tag("newcomment[post_id]", @post.id) %>

    <%= submit_tag("Submit")%>
<% end %>


<p><%= link_to 'Back to index', :controller => 'posts', :action => 'index' %></p>